/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TP3_H_RPCGEN
#define _TP3_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct cellule *liste;
#define MAXNOM 255

typedef char *type_nom;

struct cellule {
	type_nom donnee;
	liste suivant;
};
typedef struct cellule cellule;

struct arg_writte {
	type_nom nom_fichier;
	int ecraser;
	liste *donnees;
};
typedef struct arg_writte arg_writte;

#define TP3 0x20000088
#define TP31 1

#if defined(__STDC__) || defined(__cplusplus)
#define LS 1
extern  liste * ls_1(char *, CLIENT *);
extern  liste * ls_1_svc(char *, struct svc_req *);
#define READ 2
extern  liste * read_1(char *, CLIENT *);
extern  liste * read_1_svc(char *, struct svc_req *);
#define WRITTE 3
extern  void * writte_1(arg_writte *, CLIENT *);
extern  void * writte_1_svc(arg_writte *, struct svc_req *);
extern int tp3_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LS 1
extern  liste * ls_1();
extern  liste * ls_1_svc();
#define READ 2
extern  liste * read_1();
extern  liste * read_1_svc();
#define WRITTE 3
extern  void * writte_1();
extern  void * writte_1_svc();
extern int tp3_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_liste (XDR *, liste*);
extern  bool_t xdr_type_nom (XDR *, type_nom*);
extern  bool_t xdr_cellule (XDR *, cellule*);
extern  bool_t xdr_arg_writte (XDR *, arg_writte*);

#else /* K&R C */
extern bool_t xdr_liste ();
extern bool_t xdr_type_nom ();
extern bool_t xdr_cellule ();
extern bool_t xdr_arg_writte ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TP3_H_RPCGEN */
