/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tp3.h"

bool_t
xdr_liste (XDR *xdrs, liste *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct cellule), (xdrproc_t) xdr_cellule))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_type_nom (XDR *xdrs, type_nom *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNOM))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cellule (XDR *xdrs, cellule *objp)
{
	register int32_t *buf;

	 if (!xdr_type_nom (xdrs, &objp->donnee))
		 return FALSE;
	 if (!xdr_liste (xdrs, &objp->suivant))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_arg_writte (XDR *xdrs, arg_writte *objp)
{
	register int32_t *buf;

	 if (!xdr_type_nom (xdrs, &objp->nom_fichier))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ecraser))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->donnees, sizeof (liste), (xdrproc_t) xdr_liste))
		 return FALSE;
	return TRUE;
}
